# LOAD LIBRARIES 
```{r}
library(devtools)
install("C:/Users/ASUS/Documents/dlnm")
load_all("C:/Users/ASUS/Documents/dlnm")
library(epiDisplay); library(lubridate) ; library(dplyr); library(tidyr); library(plyr)
library(splines); library(gnm); library(Epi); library(tsModel); library(meta); library(sf) 
library(data.table); library(viridis)
library(mgcv) ; library(corrplot) ; library(mixmeta)
library(ggplot2) ; library(patchwork)
source("plot_exposure_lag.R")
source("plot_exposure_response.R")
```

# CORRELATION ANALYSIS
```{r}
# Calculate the correlation table
correlation_table <- cor(data[, .(PM25, PM10, NO2, O3, SO2, CO, Temp, RH)], method = "spearman")

# Print the correlation table
corrplot(correlation_table, method = "shade", shade.col = NA, tl.col = "black", tl.srt = 45)
```

# EXPOSURE-LAG-RESPONSE GRAPHS
# MERGE ALL RESULTS
```{r}
#load results_list
results_list_group <- readRDS("2_step_results_100k.rds")
results_list_ur <- readRDS("2_step_urb_rur_100k.rds")
results_bipol <- readRDS("2_step_bipol_100k.rds")

# Combine the all_CA sub-groups
combined_all_CA <- c(results_list_group$all_CA, results_bipol$all_CA)

# Combine the lists
results_list <- c(results_list_group, results_list_ur, results_bipol)
results_list$all_CA <- NULL
results_list$all_CA <- combined_all_CA
```

# PLOT EXP-RES GRAPHS  
```{r}
colors <- c("black","salmon2", "green4")
groups <- c("all_CA", "urban", "rural")
ylim <- c(0.995, 1.005)
plot_exposure_response(results_list, "PM25", groups, colors, ylim, "graphs/PM25_ur.jpeg")

colors <- c("black","salmon2", "green4")
groups <- c("all_CA", "urban", "rural")
ylim <- c(0.995, 1.005)
plot_exposure_response(results_list, "PM10", groups, colors, ylim, "graphs/PM10_ur.jpeg")

colors <- c("black","deepskyblue", "salmon")
groups <- c("all_CA", "male", "female")
ylim <- c(0.995, 1.005)
plot_exposure_response(results_list, "O3", groups, colors, ylim, "graphs/O3_sex.jpeg")

colors <- c("black","deepskyblue", "salmon")
groups <- c("all_CA", "male", "female")
ylim <- c(0.91, 1.07)
plot_exposure_response(results_list, "SO2", groups, colors, ylim, "graphs/SO2_sex.jpeg")

colors <- c("black","deepskyblue", "salmon")
groups <- c("all_CA", "male", "female")
ylim <- c(0.995, 1.005)
plot_exposure_response(results_list, "O3", groups, colors, ylim, "graphs/o3_sex.jpeg")

colors <- c("black","salmon2", "green4")
groups <- c("all_CA", "urban", "rural")
ylim <- c(0.995, 1.005)
plot_exposure_response(results_list, "O3", groups, colors, ylim, "graphs/o3_ur.jpeg")

colors <- c("black","salmon2", "green4")
groups <- c("all_CA", "adult", "senior")
ylim <- c(0.999, 1.001)
plot_exposure_response(results_list, "CO", groups, colors, ylim, "graphs/co_age.jpeg")

```

# PLOT EXP-LAG GRAPHS 
```{r}
plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "O3", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex", "graphs/o3_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "PM25", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex", "graphs/pm25_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "PM10", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex","graphs/pm10_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "NO2", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex", "graphs/no2_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "SO2", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex","graphs/so2_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "male", "female", "adult", "senior"), "CO", c("all_CA" = "black", "male" = "deepskyblue", "female" = "purple3", "adult" = "darkolivegreen3", "senior" = "orange"), "age-sex", "graphs/co_age_sex.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "NO2", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/no2_urban_rural.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "O3", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/o3_urban_rural.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "PM25", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/pm25_urban_rural.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "PM10", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/pm10_urban_rural.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "SO2", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/so2_urban_rural.jpeg")

plot_exposure_lag(results_list, c("all_CA", "urban", "rural"), "CO", c("all_CA" = "black", "urban" = "salmon2", "rural" = "darkolivegreen3"), "location", "graphs/CO_urban_rural.jpeg")
```

```{r}
# Define the pollutants
pollutants <- c("PM25", "NO2", "O3", "SO2", "CO")

for (pollutant in pollutants) {
  # Extract the results for the current pollutant and its combinations
  results <- results_list$all_CA[[pollutant]]$results_lag
  results_PM25 <- results_list$all_CA[[paste0(pollutant, "_PM25")]]$results_lag
  results_O3 <- results_list$all_CA[[paste0(pollutant, "_O3")]]$results_lag
  results_NO2 <- results_list$all_CA[[paste0(pollutant, "_NO2")]]$results_lag
  results_SO2 <- results_list$all_CA[[paste0(pollutant, "_SO2")]]$results_lag
  results_CO <- results_list$all_CA[[paste0(pollutant, "_CO")]]$results_lag
  
  # Add a column for each dataset indicating the pollutant
  results$pollutant <- pollutant
  results_PM25$pollutant <- paste0(pollutant, " + PM25")
  results_O3$pollutant <- paste0(pollutant, " + O3")
  results_NO2$pollutant <- paste0(pollutant, " + NO2")
  results_SO2$pollutant <- paste0(pollutant, " + SO2")
  results_CO$pollutant <- paste0(pollutant, " + CO")
  
  # Combine the results
  result_bipol <- bind_rows(results, results_PM25, results_O3, results_NO2, results_SO2, results_CO)
  result_bipol$label <- ifelse(result_bipol$pvalue < 0.05, "*", "")
  # Construct the file name dynamically
  file_name <- paste0("graphs/bipol_", pollutant, ".jpeg")
  # Create the plot
  
  p <- ggplot(result_bipol, aes(x = lag, y = RR, color = pollutant)) +
    geom_point(position = position_dodge(width = 0.5), size = 0.85) +
    geom_errorbar(aes(ymin = ci_low, ymax = ci_high), width = 0.3, position = position_dodge(width = 0.5)) +
    geom_hline(yintercept = 1, color = "black", linetype = "dotted") +
    labs(title = paste0(pollutant, " bipol"), x = "Lag", y = "RR") +
    scale_x_continuous(breaks = unique(result_bipol$lag)) +
    geom_text(aes(label = label, y = ci_high), vjust=0, position = position_dodge(0.5), show.legend = FALSE) +
    theme_minimal() + 
    theme(panel.grid.major.x = element_line(color = "grey90"),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_line(color = "grey90"),  
          panel.grid.minor.y = element_line(color = "grey90")) +
    guides(color = guide_legend(title = NULL))
    ggsave(file_name, plot = p, width = 6.25, height = 3.75, dpi = 400, quality = 100)
}
```



